# Generated by Django 2.0.7 on 2018-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_category',
        ),
        migrations.RenameField(
            model_name='uploaditem',
            old_name='image_big',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='uploaditem',
            name='image_small',
        ),
        migrations.AlterField(
            model_name='uploaditem',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Restaurants', 'Hotels and Restaurants'), ('Sports', 'Books and Sports'), ('Automobiles', 'Automobiles and Furnitures'), ('Other', 'Other')], default='', max_length=256),
        ),
    ]
